version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/scripts
hooks:
# During the ApplicationStart deployment lifecycle event, run the commands
#   in the script specified in "location".
  ApplicationStart:
    - location: deploy
      timeout: 600
      runas: ubuntu