version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/scripts
permissions:
  - object: /home/ubuntu/scripts
    pattern: deploy
    mode: 755
hooks:
# During the ApplicationStart deployment lifecycle event, run the commands
#   in the script specified in "location".
  ApplicationStart:
    - location: deploy
      timeout: 600
      runas: ubuntu