#!/bin/bash

image_host="${DOCKERHUB_HOST_ACCOUNT}"
tag=`git rev-parse HEAD`
tag_name=yellr_deploy:deploy_${tag}
compose_file_string=`cat ./travis/docker-compose.deploy_template.yml`
image_name=${image_host}/${tag_name}

echo "Git build SHA will be ${tag}"
echo "Local image tag will be called ${tag_name}"
echo "Built image will be pushed as ${image_name}"
echo "You will find the compose file at: docker_releases/docker-compose.yml"

rm -rf ./yellr_release.zip
rm -rf ./docker_releases
mkdir docker_releases

cp -f ./config/prod.secret.travis.exs ./config/prod.secret.exs
cp -f ./travis/docker-compose.yml ./docker/release/docker-compose.yml

set -x
./docker_compile_release && \
  cp docker/release/yellr_release.zip ./ && \
  docker build -f docker/deploy/Dockerfile -t ${tag_name} . && \
  docker tag ${tag_name} ${image_name} && \
  docker push ${image_name}
set +x

echo "${compose_file_string/SUBSTITUTE_RELEASE_IMAGE_NAME_HERE/$image_name}" > docker_releases/docker-compose.yml.1
compose_host_file_string=`cat ./docker_releases/docker-compose.yml.1`
echo "${compose_host_file_string/SUBSTITUTE_DEPLOY_HOST_NAME_HERE/$TRAVIS_DEPLOY_HOSTNAME}" > docker_releases/docker-compose.yml

deploy_file_string=`cat ./travis/deploy`
echo "${deploy_file_string/SUBSTITUTE_RELEASE_IMAGE_NAME_HERE/$image_name}" > docker_releases/deploy
chmod u+x echo ./docker_releases/deploy

cp ./travis/appspec.yml ./docker_releases/

pushd docker_release && zip yellr.zip deploy docker-compose.yml appspec.yml && popd